### ISSUE TITLE
Percentage in Y axis?

### ISSUE THREAD

**Issue by ignacio82** [hrbrmstr/taucharts#8]
Is it possible change this graph to display percentages in the y axis? (5%, 10%, 15%, 20%)

```
DF <-
  structure(
    list(
      Ranking = structure(
        1:5, .Label = c("Bottom", "Bellow Average",
                        "Average", "Above Average", "Top"), class = "factor"
      ), Prob = c(20L,
                  20L, 20L, 20L, 20L)
    ), .Names = c("Ranking", "Prob"), row.names = c(NA,-5L), class = "data.frame"
  )

tauchart(DF) %>% tau_bar(x = "Ranking", y = "Prob")
```

Thanks!

**Comment by hrbrmstr** [comment]
Hey @ignacio82. You can def do this via [D3 format specifiers](https://github.com/mbostock/d3/wiki/Formatting#d3_format) (which is in the help on `?tau_guide_y` or [tauCharts API docs](http://api.taucharts.com/basic/guide.html#ticks)). Since you want a percentage, you'll need to make sure `Prob` is in decimal format and then just supply the format:

```
library(taucharts)

DF <-
  structure(
    list(
      Ranking = structure(
        1:5, .Label = c("Bottom", "Bellow Average",
                        "Average", "Above Average", "Top"), class = "factor"
      ), Prob = c(20L,
                  20L, 20L, 20L, 20L)/100
    ), .Names = c("Ranking", "Prob"), row.names = c(NA,-5L), class = "data.frame"
  )

tauchart(DF) %>% 
  tau_bar(x="Ranking", y="Prob") %>% 
  tau_guide_y(tick_format="%")
```

![image](https://cloud.githubusercontent.com/assets/509878/9063461/7e53534c-3a95-11e5-917a-83caa2c62e5c.png)
